### ISSUE TITLE
C language equivalent?

### ISSUE THREAD

**Issue by ronbaby** [leejo/string-crc32#8]
Greeting.  I'm working on a project and this Perl package has already proven to be very helpful.  I'm thinking about a future project however where it might also be quite helpful to be able to compute the exact same output CRC32 values for the exact same input strings, but in C, in addition to Perl.

Could you tell me where I might be able to find a C function that produces that exact same output for the exact same inputs as this Perl package?

**Comment by leejo** [comment]
Hello! This module is implemented using Perl's XS layer so is mostly C code already: https://github.com/leejo/string-crc32/blob/master/CRC32.xs

HTH!
